name = "togihome-keo-lead"
main = "src/index.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "1feb21b95d0840859d902e6d4b142f60"

[triggers]
crons = ["* * * * *"]
